#clean package -P xpay
spring:
    datasource:
        url: jdbc:mysql://xpay-outnetwork.mysql.rds.aliyuncs.com:3337/xp_pay?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: online_onlinepay
        password: BMEcIpLuCJ7YWHkIn2oVdHNUUPUBFkttmZacN8qfOcNmCU5QsT9tlP9u/zjvhvGoXC4PaFsA6zEf4L9FVvqbeg==
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
    redis:
       database: 0
       host: redis-zuyong.redis.rds.aliyuncs.com
       port: 6381
       password: redis@wk2020@#1243&56*87
       timeout: 10000
       lettuce:
         pool:
          max-active: 8
          max-wait: 1000
          max-idle: 300
          min-idle: 0

onlinepay:
  project:
    shortName:  produce-xpay
    actualName: xpay
    domainName: http://hacker.huashuo2020.com
    successUrl: http://hacker.huashuo2020.com/xpay/success
    baseUrl: ${onlinepay.project.domainName}/${onlinepay.project.actualName} # 基础路径