#clean package -P test
spring:
  datasource:
    url: jdbc:mysql://47.52.221.66:3337/onlinepay?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: QuickPay@onlinepay
    password: BMEcIpLuCJ7YWHkIn2oVdHNUUPUBFkttmZacN8qfOcNmCU5QsT9tlP9u/zjvhvGoXC4PaFsA6zEf4L9FVvqbeg==
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: MYSQL
    show-sql: true
  redis:
    database: 0
    host: 47.52.221.66
    port: 6381
    password: QuickPay@2018N10Y26R@CNM
    timeout: 10000
    lettuce:
      pool:
        max-active: 8
        max-wait: 1000
        max-idle: 300
        min-idle: 0

onlinepay:
  project:
    shortName:  test-xpay
    actualName: xpay
    domainName:  http://boss.hawkeyepay.cn
    successUrl: http://online.toxpay.com/onlinepay/success