#clean package -P xpay
spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3337/onlinepay?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
        username: QuickPay@onlinepay
        password: BMEcIpLuCJ7YWHkIn2oVdHNUUPUBFkttmZacN8qfOcNmCU5QsT9tlP9u/zjvhvGoXC4PaFsA6zEf4L9FVvqbeg==
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        database: MYSQL
        show-sql: true
    redis:
       database: 0
       host: 127.0.0.1
       port: 6381
       password: QuickPay@2018N10Y26R@CNM
       timeout: 10000
       lettuce:
         pool:
          max-active: 8
          max-wait: 1000
          max-idle: 300
          min-idle: 0

onlinepay:
  project:
    shortName:  produce-xpay
    actualName: xpay
    domainName: http://boss.hawkeyepay.cn
    successUrl: http://online.toxpay.com/xpay/success
    baseUrl: ${onlinepay.project.domainName}/${onlinepay.project.actualName} # 基础路径